/*
 Generated by typeshare 1.13.2
*/

export enum CargoKind {
	Butterfly = "butterfly",
	Leaf = "leaf",
	Cloud = "cloud",
	Drip = "drip",
}

export enum CargoStatus {
	Shipping = "shipping",
	Delivered = "delivered",
	Launched = "launched",
}

export interface Cargo {
	id: number;
	createdAt: Date;
	paintTime: number;
	kind: CargoKind;
	status: CargoStatus;
}

export interface CargoInput {
	paintTime: number;
	kind: CargoKind;
}

export interface CargoRequest {
	cargoKind: CargoKind;
	paintTime: number;
}

