/*
 Generated by typeshare 1.13.4
*/

export enum CargoKind {
	Butterfly = "butterfly",
	Leaf = "leaf",
	Cloud = "cloud",
	Drip = "drip",
}

export enum CargoStatus {
	Shipping = "shipping",
	Delivered = "delivered",
	Launched = "launched",
}

export interface Cargo {
	id: number;
	createdAt: Date;
	paintTime: number;
	kind: CargoKind;
	status: CargoStatus;
}

export interface CargoInput {
	paintTime: number;
	kind: CargoKind;
}

export interface CargoRequest {
	cargoKind: CargoKind;
	paintTime: number;
}

/**
 * Custom JSON reviver and replacer functions for dynamic data transformation
 * ReviverFunc is used during JSON parsing to detect and transform specific data structures
 * ReplacerFunc is used during JSON serialization to modify certain values before stringifying.
 * These functions allow for flexible encoding and decoding of data, ensuring that complex types are properly handled when converting between TS objects and JSON
 */
export const ReviverFunc = (key: string, value: unknown): unknown => {
    if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(value) && (key === "createdAt")) {
        return new Date(value);
    }
    return value;
};

export const ReplacerFunc = (key: string, value: unknown): unknown => {
    if (value instanceof Date) {
        return value.toISOString();
    }
    return value;
};
