-- migrate:up
CREATE TYPE cargo_status AS ENUM ('shipping', 'delivered', 'launched');
CREATE TYPE cargo_kind AS ENUM ('butterfly', 'leaf', 'cloud', 'drop');

CREATE TABLE IF NOT EXISTS cargo
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paint_time INTEGER      NOT NULL,
    kind       cargo_kind   NOT NULL,
    status     cargo_status NOT NULL default 'shipping'
);

CREATE TABLE IF NOT EXISTS news
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      TEXT        NOT NULL,
    hype       INT         NOT NULL DEFAULT 0
);


-- migrate:down
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS cargo;

DROP TYPE IF EXISTS cargo_kind;
DROP TYPE IF EXISTS cargo_status;

